name: Build wheels

on:
  push:
    branches:
      - main
      - pybind11setup

jobs:
  build_wheels:
    name: Build ${{ matrix.os }} ${{ matrix.py }} ${{ matrix.arch }}
    runs-on: ${{ matrix.os }}-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - {"os": "ubuntu", "py": "cp38", "arch": "x86_64"}
          - {"os": "ubuntu", "py": "cp38", "arch": "i686"}
          - {"os": "ubuntu", "py": "cp38", "arch": "aarch64"}
          - {"os": "ubuntu", "py": "cp39", "arch": "x86_64"}
          - {"os": "ubuntu", "py": "cp39", "arch": "i686"}
          - {"os": "ubuntu", "py": "cp39", "arch": "aarch64"}
          - {"os": "macos", "py": "cp38", "arch": "x86_64"}
          - {"os": "macos", "py": "cp39", "arch": "x86_64"}
          - {"os": "windows", "py": "cp38", "arch": "x86"}
          - {"os": "windows", "py": "cp38", "arch": "AMD64"}
          - {"os": "windows", "py": "cp39", "arch": "x86"}
          - {"os": "windows", "py": "cp39", "arch": "AMD64"}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.2.2
        env:
          CIBW_BUILD_VERBOSITY: 2

      - name: Save wheels
        uses: actions/upload-artifact@v2
        with:
          path: ./wheelhouse/*.whl

  sdist:
    name: Build source distro
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Build sdist
        run: pipx run build --sdist

      - name: List
        run: |
          ls -al dist/

          #      - name: "Upload sdist"
          #        uses: actions/upload-artifact@v2
          #        with:
          #          name: dist
          #          path: dist/*.tar.gz
