name: Build wheels

on:
  push:
    branches:
      - main
      - pybind11setup

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python: [38, 39]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.2.2

      - name: Save wheels
        uses: actions/upload-artifact@v2
        with:
          path: ./wheelhouse/*.whl
